# ios/Podfile
platform :ios, '15.0' # ★ここを14.0に変更

# Flutterの設定読み込み
def flutter_root
  generated_flutter_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_flutter_build_settings_path)
    raise "#{generated_flutter_build_settings_path} must exist. Run flutter pub get first."
  end

  File.foreach(generated_flutter_build_settings_path) do |line|
    matches = line.match(/\s*FLUTTER_ROOT\s*=\s*(.*)/)
    return matches[1].strip if matches
  end
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # ★ここも14.0に強制変更して、古い設定を上書きします
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end